#1
print("Hello World")

#2
name = input("Enter name: ")
print("You name:", name)

#3
n1 = int(input("Enter a number: "))
print("Number:", n1)    

#4
float_no = float(n1)
print("Floating point number:", float_no)

#5
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

add= num1 + num2
sub = num1 - num2
mul = num1 * num2
div = num1 / num2

print("Addition:", add)
print("Subtraction:", sub)
print("Multiplication:", mul)
print("Division:", div)

#6
quotient = num1 // num2
remainder = num1 % num2

print("Quotient:", quotient)
print("Remainder:", remainder)

#7
print("Name: darshan joshi")
print("Age: 21")
print("Address: 101 aman pg")

#8
name = input("Enter your name: ")
print("Hello", name)

#9
str = input("Enter a string: ")
print(str * 3)
