# 1
meters = int(input("Enter meters: "))
kilometers = meters / 1000
print("kilometers is ",kilometers)

# 2
length = int(input("Enter the length of the rectangle: "))
breadth = int(input("Enter the breadth of the rectangle: "))
rectangle = length * breadth
print("rectangle is", rectangle)

# 3
side = int(input("Enter length of the cube: "))
cube = side ** 3
print("cube is ", cube)

# 4
base = int(input("Enter no: "))
height = int(input("Enter the height of the triangle: "))
triangle = (base * height) / 2
print("triangle is", triangle)

# 5
fahrenheit = int(input("Enter temperature in Fahrenheit: "))
celsius = (fahrenheit - 32) / 1.8
print("Celsius", celsius)

# 6
celsius = int(input("Enter Celsius: "))
fahrenheit = celsius * (9/5) + 32
print("Fahrenheit", fahrenheit)

# 7
number = int(input("Enter an integer: "))
print("Binary :", bin(number))
print("Octal :", oct(number))
print("Hexadecimal :", hex(number))
# 8
binary = input("Enter a binary number: ")
octal = input("Enter an octal number: ")
hexadecimal = input("Enter a hexadecimal number: ")
print(int(binary))
print(int(octal))
print(int(hexadecimal))
      

# 9
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
print((num1 > num2))

# Example content for Day 2
print("This is Day 2 of Python programming.")
