# 1
print("I like \"Python Programming\" very much\nIt is my favorite subject")

# 2
string = "I like \"Python Programming\" very much\nIt is my favorite subject"
print(string[27:37])

# 3
print(string[-5:])

# 4
print(string.split('\n')[1])

# 5
str1 = input("Enter first string: ")
str2 = input("Enter second string: ")
print(str1 + str2)

# 6
num = int(input("Enter a number: "))
str3 = input("Enter a string: ")
print(str3 * num," ")

# 7
char = input("Enter a character: ")
if char in string:
    print(char," is present in the string.")
else:
    print(char," is not present in the string.")

# Example content for Day 3
print("This is Day 3 of Python programming.")

